
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'a b S : a E  E : A\n          | B  A : a A\n          | B  B : b B\n          | b empty  empty : '
    
_lr_action_items = {'a':([0,1,3,],[1,3,3,]),'b':([1,3,5,],[5,5,5,]),'$end':([2,4,5,6,7,8,9,10,11,],[0,-2,-8,-1,-3,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'A':([1,3,],[4,8,]),'S':([0,],[2,]),'B':([1,3,5,],[7,9,10,]),'E':([1,],[6,]),'empty':([5,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> a E','S',2,'p_S','grammar8.py',16),
  ('E -> A','E',1,'p_E','grammar8.py',20),
  ('E -> B','E',1,'p_E','grammar8.py',21),
  ('A -> a A','A',2,'p_A','grammar8.py',25),
  ('A -> B','A',1,'p_A','grammar8.py',26),
  ('B -> b B','B',2,'p_B','grammar8.py',30),
  ('B -> b empty','B',2,'p_B','grammar8.py',31),
  ('empty -> <empty>','empty',0,'p_empty','grammar8.py',35),
]
